# Generated by Django 2.2.8 on 2020-10-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201025_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Files',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Upload Result'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='JEE/GATE Rank'),
        ),
    ]
