# Generated by Django 2.2.8 on 2020-10-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201025_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Files',
            new_name='result_file',
        ),
    ]
