# Generated by Django 2.2.8 on 2020-10-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201025_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='result_file',
            field=models.ImageField(blank=True, null=True, upload_to='files/', verbose_name='Upload Result'),
        ),
    ]
