# Generated by Django 2.2.8 on 2020-10-28 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201026_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='upi',
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_account',
            field=models.CharField(default='...00', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='ifsc_code',
            field=models.CharField(default='...ABCD', max_length=100),
        ),
        migrations.AlterField(
            model_name='assignrequest',
            name='id_alloted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EmailID'),
        ),
        migrations.AlterField(
            model_name='emailid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
