# Generated by Django 2.2.8 on 2020-10-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201028_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_holder_name',
            field=models.CharField(default='...ABCD', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='upi_id',
            field=models.CharField(default='..optional', max_length=100),
        ),
    ]
