# Generated by Django 2.2.8 on 2020-10-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201030_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='upi_id',
            new_name='upi',
        ),
    ]
