# Generated by Django 2.2.8 on 2020-11-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sendmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='all_active',
            field=models.BooleanField(default=False),
        ),
    ]
