# Generated by Django 2.2.8 on 2020-11-10 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_sendmessage_all_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='send_to_members',
            field=models.BooleanField(default=False),
        ),
    ]
