# Generated by Django 2.2.8 on 2020-11-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201110_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='members',
            field=models.ManyToManyField(to='core.Profile'),
        ),
    ]
