# Generated by Django 2.2.8 on 2020-11-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201110_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='core.Profile'),
        ),
    ]
