# Generated by Django 2.2.8 on 2020-11-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201110_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessage',
            name='members',
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Profile'),
        ),
    ]
