# Generated by Django 2.2.8 on 2020-11-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201110_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessage',
            name='members',
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='members',
            field=models.ManyToManyField(to='core.Profile'),
        ),
    ]
