# Generated by Django 2.2.8 on 2020-11-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201110_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subject_message',
            field=models.CharField(default='StudentsEarn...', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
    ]
